version: "3.2"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php_network

  php:
    image: php:7-fpm
    volumes:
      - ./code:/code
    networks:
      - php_network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "SilneHasloNieDoZlamania"

  adminer:
    image: adminer
    restart: always
    volumes:
      - vol_mysql:/var/lib/mysql
    ports:
      - 8082:8080

volumes:
  vol_mysql:

networks:
  php_network:
