version: "3.2"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 400M
        reservations:
          cpus: '0.5'
          memory: 200M

  php:
    image: php:7-fpm
    volumes:
      - ./code:/code
    networks:
      - php_network
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 400M
        reservations:
          cpus: '0.5'
          memory: 200M

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "SilneHasloNieDoZlamania"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '1'
          memory: 400M
        reservations:
          cpus: '0.5'
          memory: 200M

  adminer:
    image: adminer
    volumes:
      - vol_mysql:/var/lib/mysql
    ports:
      - 8085:8080
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8083:8080
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  vol_mysql:

networks:
  php_network:
